name: ci

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Создание переменных окружения
        run: |
          echo "${{ secrets.ENV_PROD_FILE }}" > .env.production

      - name: Настройка QEMU
        uses: docker/setup-qemu-action@v3
      - name: Настройка Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Авторизация в Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ellechildbot:latest
          build-args: ${{ secrets.ENV_PROD_FILE }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@v3
      - name: Деплой образа
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOSTNAME}}
          USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '

          cd /home/${{ secrets.SSH_USERNAME }}/projects/elle && ./run.sh
