name: ci

on:
  push:
    branches: ['main']

jobs:
  buildy:
    runs-on: ubuntu-latest

    #needs:
    #  - testing

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Авторизация в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Создание переменных окружения
        run: |
          echo "${{ secrets.ENV_PROD_FILE }}" > .env.production

      - name: Сборка и пуш образа
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ellechildbot:latest
          build-args: ${{ secrets.ENV_PROD_FILE }}
